---
- hosts: all
  tasks: 
    - name: ensure apache2
      apt:
        name: apache2
        state: latest
      notify: startapache2
  handlers:
    - name: startapache2
      service:
        name: apache2
        state: started